# Change these first
owner: desisn # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: desisn.de
    url: https://desisn.de
  - name: dico-mediadesign.de
    url: https://dico-mediadesign.de
  - name: seanlina.com
    url: https://seanlina.com
  - name: bchirg.de
    url: https://bchirg.de
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime # where "repo" is your repository name
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/desisn/upptime/blob/master/assets/logo.png
  name: desisn websites monitor | Upptime 
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page for our client websites which uses **real-time** data from our [GitHub repository](https://desisn.github.io/upptime/). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
